#!/usr/bin/env python3

import os
import sys
import tempfile
import importlib.machinery
from pathlib import Path

diskUtilsLoader = importlib.machinery.SourceFileLoader(
    'disk_utils', os.path.dirname(Path(__file__).absolute()) + '/disk_utils.py')
diskUtils = diskUtilsLoader.load_module()

def send_data(file_object):
    sys.stdout.buffer.write(file_object.read())



def main():
    export_compress = os.environ.get('OSP_EXPORT_COMPRESS', False)
    export_format = os.environ.get('OSP_EXPORT_IMPORT_FORMAT', 'qcow2')
    memory_temp_dir = os.environ.get('OSP_EXPORT_IMPORT_MEMORY_TEMPORARY_DIR', '/tmp')
    diskUtils.raise_if_unsupported_disk_format(export_format)

    with tempfile.NamedTemporaryFile(mode='rb', dir=memory_temp_dir) as tmpfile:
        diskUtils.from_raw_to(export_format)(str(os.environ['EXPORT_DEVICE']), tmpfile.name, compress=bool(export_compress))
        send_data(tmpfile)

if __name__ == '__main__':
    main()
