#!/usr/bin/env python3

import os
import sys
import tempfile
import importlib.machinery
from pathlib import Path

diskUtilsLoader = importlib.machinery.SourceFileLoader(
    'disk_utils', os.path.dirname(Path(__file__).absolute()) + '/disk_utils.py')
diskUtils = diskUtilsLoader.load_module()

def read_data(file_object):
    file_object.write(sys.stdin.buffer.read())

def main():
    import_format = os.environ.get('OSP_EXPORT_IMPORT_FORMAT', 'vmdk')
    prefix_temp_file = os.environ.get('OSP_EXPORT_IMPORT_PREFIX_TEMPORARY_FILE', '/tmp')

    diskUtils.raise_if_unsupported_disk_format(import_format)

    with tempfile.NamedTemporaryFile(mode='wb', prefix=prefix_temp_file) as tmpfile:
        read_data(tmpfile)
        diskUtils.to_raw_from(import_format)(tmpfile.name, str(os.environ['IMPORT_DEVICE']))

if __name__ == '__main__':
    main()
